### ISSUE TITLE
Collection of Usage Statistics

### ISSUE THREAD

**Issue by wai2k** [cellcounter/cellcounter#370]
I was wondering if we could get more granular statistics on the number of cells counted and how many differentials have been performed.

So I was thinking of collecting

How many differentials have been performed. This would be logged if the user presses 'reset' AND if the count is >99 (or whatever number we decide)

How many cells are counted. If the above conditions are met.

What do you think??

**Comment by jvc26** [comment]
Eminently doable, could you outline the most useful data, and I can pull
together an API for it?

**Comment by wai2k** [comment]
The data I would like to collect is

- How many differential performed - The only way that we are going to capture this is to assume that everytime someone presses **reset** they have completed a count.
- What is the cell count the moment that they press 'reset'
- Their IP address (*up for discussion given potential privacy issues*)

I appreciate that this way you will miss the counts that people make when they do not press **reset**. Unless **close window/ tab** can trigger an event to record the count at that moment too?

**Comment by wai2k** [comment]
I think we should capture a datetime stamp too. Interesting to see if total counts drift as we near Friday and home time!!!

**Comment by jvc26** [comment]
Assigned to @oghm2 - have you had any chance to progress this?

**Comment by oghm2** [comment]
Yeah, I'll look at it this week.

Olly

**Comment by wai2k** [comment]
Great stuff! Let me know how it goes.

**Comment by jvc26** [comment]
What do you want to use as the threshold for counting?

**Comment by wai2k** [comment]
Can we collect everything thing and apply the threshold post-hoc?

But to start, we can use a threshold of 75. People rarely count below 100
and playing around, they rarely reach 75.

**Comment by wai2k** [comment]
Possible triggers for counts:-

1. 'Reset Counter'
2. Everytime the user closes keyboard either by clicking 'Close and display
results' or Clicks outside the keyboard.

Number 2 might be more reliable as that will overcome the issue with people
not pressing reset if they no longer want to count anymore and just close
the whole window.

**Comment by haematologic** [comment]
Sounds good! Close and reset are good triggers, combined with a count of 75
or more.

Best,

D

**Comment by jvc26** [comment]
I've implemented it as submit on closure of keyboard, cutoff 75 at present. It is ratelimited to 1/min per IP address, which should reduce spam (this threshold can be increased, of course). What it won't account for, however, is people who close, reopen, and close again - that will take a bit more changing.

**Comment by wai2k** [comment]
Thanks! I've actually COMPLETELY missed this. Thank you for doing this. I
think this will work. I don't think many people will close, reopen, close
again. I guess that this is no easy way to remember the counting 'session'
that only gets 'reset' when the close a the windows or press reset.

Don't worry about it for the time being.

How can we 'view' the statistics?

**Comment by wai2k** [comment]
But THANK YOU!! once again. We can put it on the front page once we have
gathered more stats.

My colleague brought up the fact that they would love to have personal
statistics on how many bone marrows they have looked at and if there is
away that they can keep and audit log of the bone marrows that have
'diffed' as a record of their experience and work! <- GREAT idea and one
with immense value.

**Comment by wai2k** [comment]
Oh, are you capturing the ip address as well?

**Comment by jvc26** [comment]
At present, no. All it captures is the total count. There is a lot of scope to add to this data, but we need to think about what we collect, and how much. Have a think about the kind of data ideally would be wanted for usage stats and for personal recording (i.e. experience logs). We can then set up a datastore which facilitates those, within limits of avoiding PII.

**Comment by wai2k** [comment]
Thanks James. This is a great start.

The only reason I ask about the IP is because I want to know how many
counts per IP address.

Any UI to the data collected so far?

**Comment by jvc26** [comment]
No data collected so far as this hasn't been merged into the mainline
pending discussion with @oghm2 and further tweaks to the database
models/API.

It will have a UI eventually but so far just implemented a very basic API.

**Comment by wai2k** [comment]
Cool! Thanks for letting me know.



On 14 Aug 2015, at 18:54, James Clemence <notifications@github.com> wrote:

No data collected so far as this hasn't been merged into the mainline
pending discussion with @oghm2 and further tweaks to the database
models/API.

It will have a UI eventually but so far just implemented a very basic API.

—
Reply to this email directly or view it on GitHub
<https://github.com/cellcounter/cellcounter/issues/370#issuecomment-131194509>
.

**Comment by jvc26** [comment]
Few more thoughts on the above, mainly aimed at @oghm2:

1. Planning on using the ```session_key``` (non-unique, but random and probably for our purposes unique-enough) and the date hashed together SHA1, which should give us a unique indentifier for a single user on a single day (and is better than IP address as that may well be shared between multiple users at a single NHS site)
2. With the above hash, then storing the total counted cells, facilitating a more accurate count of counts performed per user per day, and also of the number of cells per count

This above process allows us to collect data about anonymous or non-anonymous users. It doesn't facilitate per-user count data storage, which I think needs a little more thought and planning, but offers us an extensible first pass at the process. Thoughts?

**Comment by wai2k** [comment]
Sounds good to me.

I would like to aim to present cell countr at the next BSH meeting in
Glasgow April 2016.

Would be good to have at least 3-4 months statistics be then.



On 7 Sep 2015, at 09:54, James Clemence <notifications@github.com> wrote:

Few more thoughts on the above, mainly aimed at @oghm2
<https://github.com/oghm2>:

   1. Planning on using the session_key (non-unique, but random and
   probably for our purposes unique-enough) and the date hashed together SHA1,
   which should give us a unique indentifier for a single user on a single day
   (and is better than IP address as that may well be shared between multiple
   users at a single NHS site)
   2. With the above hash, then storing the total counted cells,
   facilitating a more accurate count of counts performed per user per day,
   and also of the number of cells per count

This above process allows us to collect data about anonymous or
non-anonymous users. It doesn't facilitate per-user count data storage,
which I think needs a little more thought and planning, but offers us an
extensible first pass at the process. Thoughts?

—
Reply to this email directly or view it on GitHub
<https://github.com/cellcounter/cellcounter/issues/370#issuecomment-138242665>
.

**Comment by oghm2** [comment]
Hi James,

Using the session key sounds like a sensible plan and better than IP
address. I know session keys are random and not unique, but in practice
they're quite long (32 characters?) so they are probably approximately
unique. If you hash the session key with the date then you potentially lose
the ability to track a user through time (with the caveat that they might
change session key anyway). On the other hand it does keep things more
anonymous. Are we using session cookies?

Olly

**Comment by wai2k** [comment]
The kinds of data I would like to be able to see is:-

1) Average number if differentials per centre (this roughly equates to an
ip address?)
2) Average number of cells counted per differential per centre.
3) Average number of cells counter per differential per user (if the user
logs in)

Using the session key you won't be able to do any of these?
I personally think that there is nothing wrong collecting ip address if all
we are doing is collecting the total cell count per differential.

Thoughtt?

**Comment by jvc26** [comment]
> 1) Average number if differentials per centre (this roughly equates to an
> ip address?)

Difficult to know what the IP address really represents - some will be centres, but some centres may have more than one outbound IP address behind which their computers sit.

> 2) Average number of cells counted per differential per centre.

Average cells/differential is straightforward, working our which comes from the same centre is more tricky and unlikely to be reliable.

> 3) Average number of cells counter per differential per user (if the user
> logs in)

That's straightforward, and the sort of data we're able to collect with the above.

> Using the session key you won't be able to do any of these?

Not quite. Working out which IP address corresponds to a centre is likely to be error prone and inadequately reliable to draw conclusions. Using session keys allows us to differentiate between users behind a single IP address, and also allows us to make a rough split of users both anonymous and logged in, giving us the best per-user data we can aquire.

**Comment by jvc26** [comment]
> @oghm2
> If you hash the session key with the date then you potentially lose the ability to track a user through time

The caveat to this is that if a user session key regenerates, and now represents a new user, we can't say that they are different people, or necessarily the same people. What do you think is the best solution for this?

**Comment by wai2k** [comment]
Thanks James. You make very good points. I'll leave these aspects to you.

The only reason I commented on the IP address because if you go through the
IP addresses based on statistics that we have been collecting, they do seem
to correspond to individual centres.

**Comment by oghm2** [comment]
On 8 September 2015 at 09:31, James Clemence <notifications@github.com>
wrote:

> @oghm2 <https://github.com/oghm2>
> If you hash the session key with the date then you potentially lose the
> ability to track a user through time
>
> The caveat to this is that if a user session key regenerates, and now
> represents a new user, we can't say that they are different people, or
> necessarily the same people. What do you think is the best solution for
> this?
>

Yes, I take your point but equally I don't have a good feel for when the
session keys are regenerated. Reuse seems unlikely in practice given the
length of the session key.

Could we just take an experimental approach of collecting some data and
seeing how it looks? I would suggest recording the session key, the date,
the time, the IP address (or its hash if you prefer) and the relevant
counts. That way we can still use the data as you originally suggested
(i.e. combine the session key and the date) but we can also potentially
extract more useful information that might be lost if we immediately hash
the session key and the date. For example, by combining session key and IP
address it might be possible to check users in a single institution as
suggested by Wai Keong.

I don't see that anything other than user logins will guarantee reliable
data at the granularity of the user. Even in a single lab there might be
one computer used by everyone doing counts that maintains the same session
key for different actual users.

Olly

**Comment by jvc26** [comment]
> @oghm2 
> I don't see that anything other than user logins will guarantee reliable data at the granularity of the user.

Absolutely, but requiring user logins will have a negative impact on usage I think.

We'll collect some data and see what happens.

**Comment by jvc26** [comment]
@oghm2 please review cellcounter/cellcounter#393 for merge. Should implement a full basic stats app, collecting IP, session_id, and total count with a timestamp, as well as middleware to ensure there is always a session_id set.

**Comment by wai2k** [comment]
Agree! Let's do it and see what happens.

**Comment by jvc26** [comment]
Right, a further question for @oghm2 - there is an issue with the setup as currently implemented, as it sets a new session id for all comers, and anyone who doesn't return the cookie sessionid, someone can quite easily spam the site and generate hundreds of thousands of sessions. Any ideas on methods to prevent/minimise this? This isn't usually an issue, but as we're generating a session for all users, rather than just ones who have their session modified, this has a downstream impact on session numbers. This could potentially be used to deny service with enough requests.

Thoughts include:

1. Ratelimit
2. Shorter cookie duration allowing faster recycling and earlier cleanup of expired sessions
3. Bot identification (messy, and requires maintenance of a whitelist/blacklist quite inelegant)

Thoughts?

**Comment by jvc26** [comment]
After extensive discussion with @doismellburning have a resolution via using cache backends and taking session out of DB.

**Comment by doismellburning** [comment]
(Note - this doesn't solve the DoS problem; it mitigates the consequences)

**Comment by jvc26** [comment]
Probably should have said solution rather than resolution ... I think the risk/benefit is at least in line with acceptability now

**Comment by wai2k** [comment]
@doismellburning Thanks for your input once again! I'm glad you guys are thinking this through so thoroughly.

**Comment by wai2k** [comment]
Sorry to be a pain but any updates on the collection of usage statistics?
I'm very excited about this!

**Comment by jvc26** [comment]
Just working through a database issue.

**Comment by wai2k** [comment]
Thanks..

**Comment by jvc26** [comment]
This has been fixed in cellcounter/cellcounter#393
