### ISSUE TITLE
Cell count shows 0% when it is not zero but less than 1%

### ISSUE THREAD

**Issue by wai2k** [cellcounter/cellcounter#412]
This happens when a particular cell type is <1% but it still present.

For example, there might only be 1 plasma cell out of 300 cells counter but this shows up at 0% on the summary table/ text.

Potential solutions:-

 1. Show **<1%**
 1. Show one decimal place ie. **0.3%**

My preference would be to show **<1%**

**Comment by jvc26** [comment]
Missed this - will fix shortly

**Comment by jvc26** [comment]
An appropriate fix is now at cellcounter/cellcounter#419
