### ISSUE TITLE
Adjust blasts percentage when erythroid differential is >50%

### ISSUE THREAD

**Issue by wai2k** [cellcounter/cellcounter#429]
This is to overcome the issue when blasts are underestimated when the erythroid compartment is >50%. Need to think about how to actually present this.

**Comment by haematologic** [comment]
i.e. for cases with expanded erythropoiesis (>50%) where absolute blast counts are less than 20% but where % blasts with non-erythroid cells as denominator would >=20% and thus still be considered acute leukaemia i.e. AML-MRC or AEL (vs  if non erythroid cells blast % <20%)
http://www.nature.com/modpathol/journal/v21/n11/full/modpathol2008142a.html
http://www.haematologica.org/content/96/9/1241

**Comment by jvc26** [comment]
If you guys could come up with a mock/suggestion of how this is represented
and shown in the results table, I'm sure we can create something.

**Comment by wai2k** [comment]
Duncan, maybe pop by something over lunch or something and we will figure
something out!

**Comment by wai2k** [comment]
I would create a calculated item called **erythroid-adjusted blast %**. This would be calculated item like the **Myeloid/ Erythroid ratio**

The calculation would be

`'Blasts Count' / ('Total Cell Count' - 'Erythroid Count') * 100%`

This could be calculated every single time but will only show if the Erythroid count comprise >50% of the count

Therefore on the HTML view, this will only show if the erythroid >50% and similarly on the text only view.

**Comment by wai2k** [comment]
We no longer need to this as the latest WHO classification no longer requires this adjustment.
