### ISSUE TITLE
Keymaps are not being saved

### ISSUE THREAD

**Issue by wai2k** [cellcounter/cellcounter#439]
User logins
User creates a new keyboard map
'Saves as New'
Gives the key map a name
But the keyboard is not actually saved and the user can not find the keymap that they have saved

**Comment by jvc26** [comment]
Thanks. Will investigate

--
-------------------------------------
Dr James V Clemence
CT2 (Acute Medicine/Infectious Disease), Northwick Park Hospital
-------------------------------------

**Comment by jvc26** [comment]
Fixed - was an issue with [ALLOWED_HOSTS](https://docs.djangoproject.com/en/1.10/ref/settings/#allowed-hosts). This variable has been fixed.

**Comment by wai2k** [comment]
This still does not work. Look at user: AJWILSON

**Comment by jvc26** [comment]
Fix for this is now in PR. The bug was actually slightly more subtle:

1. User doesn't click 'clear keymap', save goes ahead without issue
2. User does click 'clear keymap', save fails with a 400 error, as the 'user' field is now missing
